version: '3'
services:
  web:
    build: .
    container_name: apache2_server
    network_mode: service:db
    volumes:
      - ../:/var/www/html

  db:
    image: mariadb:latest
    container_name: mariadb_server
    environment:
      MYSQL_ROOT_PASSWORD: matueRootDB
      MYSQL_DATABASE: eLibrosDB
      MYSQL_USER: matue
      MYSQL_PASSWORD: matueDB
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
