version: '3'
services:
  web:
    build: .
    container_name: apache2_server
    ports:
      - "80:80"
      - "5900:5900"
    volumes:
      - ../:/var/www/html

  db:
    image: mariadb:latest
    container_name: mariadb_server
    environment:
      MYSQL_ROOT_PASSWORD: matueRootDB
      MYSQL_DATABASE: eLibrosDB
      MYSQL_USER: matue
      MYSQL_PASSWORD: matueDB
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
